sonar.projectKey=wastebot-frontend
sonar.projectName=WasteBot Frontend
sonar.projectVersion=1.0
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/build/**,**/coverage/**,**/*.test.tsx,**/*.test.ts
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.tests=src

